### ISSUE TITLE
Suggestion: Point Tracker

### ISSUE THREAD

**Issue by rockylikespocky** [justinxxvii/python-bing-bot#7]
Would you be interested in adding a way to track points from each account? I was thinking maybe save the total points in each account to a text file and have it update each time the bot runs. I'll see if I can come up with it.

**Comment by justinxxvii** [comment]
I have this working. I'll post up the changes

**Comment by rockylikespocky** [comment]
Do you have the point tracker working?

**Comment by justinxxvii** [comment]
added in last commit
