### ISSUE TITLE
Detector Error

### ISSUE THREAD

**Issue by rockylikespocky** [justinxxvii/python-bing-bot#9]
Anyone else getting an error with the detector?

**Comment by Gishi1** [comment]
mine worked fine last night... ill let you know how mine works out tomorrow.

**Comment by rockylikespocky** [comment]
![bing_error](https://cloud.githubusercontent.com/assets/7507191/5750545/612dffc0-9c0b-11e4-988a-0c3199fbe9c7.png)

Not sure why this is happening. If yours still works think you can send me your version of the bot?

**Comment by Gishi1** [comment]
okay ya i have the error ill see what i can do to fix it...

**Comment by Gishi1** [comment]
okay this seems to work:

add this to includes:
import string

then replace this for each function for mobile and desktop search:

totalNumber = element.text[startPoint:stringLength]

replace with this:

Numbertext = element.text[startPoint:stringLength]
totalNumber = string.replace(Numbertext, ' credits', '')

**Comment by rockylikespocky** [comment]
Seems to be working for me now thanks a bunch :D

**Comment by Gishi1** [comment]
yep easy fix not the best but it works.

**Comment by justinxxvii** [comment]
Looks like they added more letters after the max credits number. Fixed this in last commit
